// ~200 common disposable/temporary email domains
export const DISPOSABLE_DOMAINS = new Set([
  'tempmail.com','guerrillamail.com','guerrillamail.info','guerrillamail.net','guerrillamail.org',
  'guerrillamail.de','yopmail.com','yopmail.fr','mailinator.com','mailinator.net',
  'throwaway.email','10minutemail.com','10minutemail.net','10minute.email','minutemail.com',
  'tempail.com','temp-mail.org','temp-mail.io','temp-mail.de','tempmailo.com',
  'dispostable.com','maildrop.cc','mailnesia.com','mailcatch.com','trashmail.com',
  'trashmail.me','trashmail.net','trashmail.org','sharklasers.com','grr.la',
  'guerrillamailblock.com','pokemail.net','spam4.me','binkmail.com','bobmail.info',
  'chammy.info','devnullmail.com','discard.email','discardmail.com','discardmail.de',
  'disposableaddress.com','disposableemailaddresses.emailmiser.com','disposeamail.com',
  'dm.w3internet.co.uk','dropmail.me','dumpmail.de','emailgo.de','emailigo.de',
  'emailsensei.com','emailtemporario.com.br','ephemail.net','etranquil.com',
  'fakeinbox.com','fakeemail.com','fastacura.com','filzmail.com','fixmail.tk',
  'flyspam.com','freemail.ms','getairmail.com','getmails.eu','getonemail.com',
  'gishpuppy.com','goemailgo.com','greensloth.com','gufum.com','haltospam.com',
  'harakirimail.com','hidemail.de','hotpop.com','iminbox.com','incognitomail.org',
  'inoutmail.de','instantemailaddress.com','jetable.com','jetable.fr.nf','jetable.net',
  'jetable.org','jnxjn.com','kasmail.com','kaspop.com','keepmymail.com',
  'killmail.com','killmail.net','klzlk.com','kurzepost.de','lawlita.com',
  'letthemeatspam.com','lhsdv.com','lifebyfood.com','link2mail.net','litedrop.com',
  'lol.ovpn.to','lookugly.com','lopl.co.cc','lortemail.dk','lovemeleaveme.com',
  'lr78.com','m4ilweb.info','maboard.com','mail-temporaire.fr','mail.mezimages.net',
  'mailbidon.com','mailblocks.com','mailexpire.com','mailforspam.com','mailfreeonline.com',
  'mailin8r.com','mailinater.com','mailincubator.com','mailme.ir','mailme.lv',
  'mailmetrash.com','mailmoat.com','mailnator.com','mailnull.com','mailshell.com',
  'mailsiphon.com','mailslite.com','mailtemp.info','mailtothis.com','mailzilla.com',
  'makemetheking.com','manifestgenerator.com','mbx.cc','mega.zik.dj','meinspamschutz.de',
  'meltmail.com','messagebeamer.de','mezimages.net','ministry-of-silly-walks.de',
  'mintemail.com','moburl.com','moncourrier.fr.nf','monemail.fr.nf','monmail.fr.nf',
  'mt2015.com','mx0.wwwnew.eu','myalias.pw','mymail-in.net','mypartyclip.de',
  'myphantom.com','mysamp.de','mytempemail.com','mytempmail.com','mytrashmail.com',
  'nabala.com','neomailbox.com','nepwk.com','nervmich.net','nervtansen.de',
  'netmails.com','netmails.net','neverbox.com','no-spam.ws','nobulk.com',
  'noclickemail.com','nogmailspam.info','nomail.xl.cx','nomail2me.com','nomorespamemails.com',
  'nospam.ze.tc','nospam4.us','nothingtoseehere.ca','nowmymail.com','nurfuerspam.de',
  'nus.edu.sg','nwldx.com','objectmail.com','obobbo.com','onewaymail.com',
  'otherinbox.com','ourklips.com','outlawspam.com','ovpn.to','owlpic.com',
  'pancakemail.com','pimpedupmyspace.com','pjjkp.com','plexolan.de','pookmail.com',
  'privacy.net','proxymail.eu','prtnx.com','putthisinyouremail.com','qq.com',
  'quickinbox.com','rcpt.at','reallymymail.com','recode.me','recursor.net',
  'regbypass.com','rejectmail.com','rhyta.com','rklips.com','rmqkr.net',
  'royal.net','rppkn.com','rtrtr.com','s0ny.net','safe-mail.net',
  'safersignup.de','safetymail.info','safetypost.de','sandelf.de','saynotospams.com',
  'scatmail.com','schafmail.de','selfdestructingmail.com','sendspamhere.com','shieldedmail.com',
  'shiftmail.com','shitmail.me','shortmail.net','sibmail.com','skeefmail.com',
  'slaskpost.se','slipry.net','slopsbox.com','smashmail.de','soodonims.com',
  'spam.la','spam.su','spamavert.com','spambob.com','spambob.net',
  'spambob.org','spambog.com','spambog.de','spambog.ru','spambox.us',
  'spamcannon.com','spamcannon.net','spamcero.com','spamcon.org','spamcorptastic.com',
  'spamcowboy.com','spamcowboy.net','spamcowboy.org','spamday.com','spamex.com',
  'spamfighter.cf','spamfighter.ga','spamfighter.gq','spamfighter.ml','spamfighter.tk',
  'spamfree24.com','spamfree24.de','spamfree24.eu','spamfree24.info','spamfree24.net',
  'spamfree24.org','spamgourmet.com','spamgourmet.net','spamgourmet.org','spamherelots.com',
  'spamhereplease.com','spamhole.com','spamify.com','spaminator.de','spamkill.info',
  'spaml.com','spaml.de','spammotel.com','spamobox.com','spamoff.de',
  'spamslicer.com','spamspot.com','spamstack.net','spamtrail.com','spamtrap.ro',
  'speed.1s.fr','suremail.info','teleworm.us','tempalias.com','tempe4mail.com',
  'tempemail.co.za','tempemail.com','tempemail.net','tempinbox.com','tempinbox.co.uk',
  'tempmail.eu','tempmail.it','tempmail2.com','tempmailer.com','tempmailer.de',
  'tempomail.fr','temporarily.de','temporarioemail.com.br','temporaryemail.net',
  'temporaryemail.us','temporaryforwarding.com','temporaryinbox.com','temporarymailaddress.com',
  'thankyou2010.com','thc.st','tittbit.in','tmail.ws','tmailinator.com',
  'toiea.com','tradermail.info','trash-amil.com','trash-mail.at','trash-mail.com',
  'trash-mail.de','trash2009.com','trashemail.de','trashymail.com','trashymail.net',
  'twinmail.de','tyldd.com','uggsrock.com','upliftnow.com','uplipht.com',
  'venompen.com','veryreallyfakeemails.com','viditag.com','viewcastmedia.com',
  'viewcastmedia.net','viewcastmedia.org','vomoto.com','vpn.st','vsimcard.com',
  'vubby.com','wasteland.rfc822.org','webemail.me','weg-werf-email.de','wegwerfadresse.de',
  'wegwerfemail.com','wegwerfemail.de','wegwerfmail.de','wegwerfmail.net','wegwerfmail.org',
  'wh4f.org','whatiaas.com','whatpaas.com','whyspam.me','wikidocuslice.com',
  'willhackforfood.biz','willselfdestruct.com','winemaven.info','wronghead.com',
  'wuzup.net','wuzupmail.net','wwwnew.eu','xagloo.com','xemaps.com',
  'xents.com','xjoi.com','xoxy.net','yapped.net','yep.it',
  'yogamaven.com','yuurok.com','zehnminuten.de','zehnminutenmail.de','zippymail.info',
  'zoaxe.com','zoemail.org','protonmail.com'
])

// Remove protonmail - it's legit. Added by mistake in some lists.
DISPOSABLE_DOMAINS.delete('protonmail.com')

export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase()
  if (!domain) return false
  return DISPOSABLE_DOMAINS.has(domain)
}
