"""
A/B Test: Engine Only vs Engine + Kalshi
Run manually — NOT part of the daily pipeline.
Created: 2026-02-23 per Josh directive.
"""
import json
import os
import shutil
from datetime import date
from kalshi_standalone import generate_comparison

TODAY = date.today().strftime('%Y-%m-%d')
ENGINE_DIR = os.path.dirname(os.path.abspath(__file__))
PICKS_DIR = os.path.join(ENGINE_DIR, f'picks_{TODAY}')
ENGINE_ONLY_DIR = os.path.join(ENGINE_DIR, f'picks_{TODAY}_engine_only')
KALSHI_DIR = os.path.join(ENGINE_DIR, f'picks_{TODAY}_engine_plus_kalshi')

def main():
    # Load engine-only NBA picks
    nba_path = os.path.join(PICKS_DIR, 'nba_spread_picks.json')
    with open(nba_path, 'r') as f:
        nba_picks = json.load(f)
    
    print(f"Loaded {len(nba_picks)} NBA engine picks for {TODAY}")
    
    # Load NCAAB picks if they exist
    ncaab_path = os.path.join(PICKS_DIR, 'ncaab_spread_picks.json')
    ncaab_picks = []
    if os.path.exists(ncaab_path):
        with open(ncaab_path, 'r') as f:
            ncaab_picks = json.load(f)
        print(f"Loaded {len(ncaab_picks)} NCAAB engine picks")
    
    # Run Kalshi comparison for NBA
    print("\n=== Fetching Kalshi NBA data... ===")
    nba_result = generate_comparison(nba_picks, TODAY)
    
    # Create engine+kalshi output directory
    os.makedirs(KALSHI_DIR, exist_ok=True)
    
    # Save blended NBA picks
    with open(os.path.join(KALSHI_DIR, 'nba_spread_picks.json'), 'w') as f:
        json.dump(nba_result['blended_picks'], f, indent=2)
    
    # Copy NCAAB picks unchanged (Kalshi doesn't have NCAAB game markets)
    if ncaab_picks:
        with open(os.path.join(KALSHI_DIR, 'ncaab_spread_picks.json'), 'w') as f:
            json.dump(ncaab_picks, f, indent=2)
    
    # Save full comparison
    with open(os.path.join(KALSHI_DIR, 'kalshi_comparison.json'), 'w') as f:
        json.dump(nba_result, f, indent=2, default=str)
    
    # Generate readable comparison markdown
    md = f"# Engine vs Engine+Kalshi — {TODAY}\n\n"
    md += f"**Kalshi weight:** {nba_result['kalshi_weight']:.0%} Kalshi / {1-nba_result['kalshi_weight']:.0%} Engine\n"
    md += f"**Games with Kalshi data:** {nba_result['games_with_kalshi']}/{nba_result['total_games']}\n"
    md += f"**Picks changed:** {nba_result['picks_changed']}\n\n"
    
    if nba_result['changes']:
        md += "## 🔄 Changed Picks\n"
        for change in nba_result['changes']:
            md += f"- {change}\n"
        md += "\n"
    
    md += "## NBA Side-by-Side\n\n"
    md += "| Game | Engine Pick | Engine Conf | Kalshi Prob | Kalshi Favors | Blended Pick | Blended Conf | Divergence | Changed? |\n"
    md += "|------|-----------|-------------|-------------|---------------|-------------|-------------|------------|----------|\n"
    
    for c in nba_result['comparison']:
        kd = c.get('kalshi_data', {})
        if isinstance(kd, str):
            kalshi_prob = 'N/A'
            kalshi_favors = 'N/A'
        elif kd:
            kalshi_favors = kd.get('kalshi_favors', 'N/A')
            kalshi_prob = f"{kd.get('kalshi_prob', 0):.1%}"
        else:
            kalshi_prob = 'N/A'
            kalshi_favors = 'N/A'
        
        div = f"{c['divergence']:.1%}" if c['divergence'] is not None else 'N/A'
        changed = '✅ YES' if c['changed'] else ''
        
        md += f"| {c['game']} | {c['engine_pick']} | {c['engine_conf']:.1%} | {kalshi_prob} | {kalshi_favors} | {c['blended_pick']} | {c['blended_conf']:.1%} | {div} | {changed} |\n"
    
    md += "\n## Key Insights\n\n"
    
    # Find biggest divergences
    divergences = [(c['game'], c['divergence']) for c in nba_result['comparison'] if c['divergence'] is not None]
    divergences.sort(key=lambda x: x[1], reverse=True)
    
    if divergences:
        md += "### Biggest Divergences (Engine vs Kalshi)\n"
        for game, div in divergences[:5]:
            md += f"- **{game}**: {div:.1%} divergence\n"
    
    md += "\n---\n*Generated by run_kalshi_comparison.py — manual A/B test, not part of daily pipeline*\n"
    
    with open(os.path.join(KALSHI_DIR, 'comparison.md'), 'w') as f:
        f.write(md)
    
    # Print summary to console
    print(f"\n{'='*60}")
    print(f"RESULTS SAVED")
    print(f"{'='*60}")
    print(f"Engine-only picks: {ENGINE_ONLY_DIR}")
    print(f"Engine+Kalshi picks: {KALSHI_DIR}")
    print(f"\nGames with Kalshi data: {nba_result['games_with_kalshi']}/{nba_result['total_games']}")
    print(f"Picks changed: {nba_result['picks_changed']}")
    
    if nba_result['changes']:
        print(f"\n🔄 CHANGED PICKS:")
        for c in nba_result['changes']:
            print(f"  → {c}")
    
    print(f"\n--- Side-by-Side ---")
    for c in nba_result['comparison']:
        kd = c.get('kalshi_data', {})
        if isinstance(kd, str):
            kalshi_str = "(no Kalshi data)"
        elif kd:
            kalshi_str = f"Kalshi: {kd.get('kalshi_favors','?')} @ {kd.get('kalshi_prob',0):.1%}"
        else:
            kalshi_str = "(no Kalshi data)"
        
        change_flag = " ← CHANGED" if c['changed'] else ""
        print(f"  {c['game']}: Engine={c['engine_pick']} ({c['engine_conf']:.1%}) | {kalshi_str} | Blended={c['blended_pick']} ({c['blended_conf']:.1%}){change_flag}")


if __name__ == '__main__':
    main()
