import Link from 'next/link'
import { TrendingUp, Heart, Phone, Globe, AlertTriangle, Shield } from 'lucide-react'

export default function ResponsibleGamblingPage() {
  return (
    <div className="min-h-screen bg-bg-primary">
      {/* Header */}
      <header className="border-b border-accent-green/20 bg-bg-secondary/50 backdrop-blur-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex justify-between items-center">
            <Link href="/" className="flex items-center space-x-2">
              <TrendingUp className="text-accent-green w-8 h-8" />
              <span className="text-2xl font-bold text-gradient">Parlay Guarantee</span>
            </Link>
            <nav className="hidden md:flex space-x-6 items-center">
              <Link href="/pricing" className="hover:text-accent-green transition-colors">Tonight&apos;s Picks</Link>
              <Link href="/results" className="hover:text-accent-green transition-colors">Results</Link>
              <Link href="/pricing" className="hover:text-accent-green transition-colors">Pricing</Link>
              <Link href="/auth/signin" className="btn-primary text-sm py-2 px-4">Sign In</Link>
            </nav>
          </div>
        </div>
      </header>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="mb-8 text-center">
          <h1 className="text-4xl font-bold mb-4 flex items-center justify-center gap-3">
            <Heart className="text-red-400 w-10 h-10" />
            Responsible Gambling
          </h1>
          <p className="text-text-muted text-lg max-w-2xl mx-auto">
            ParlayGuarantee is committed to promoting responsible gambling. Sports betting should be fun — never a financial burden.
          </p>
        </div>

        {/* Important Notice */}
        <div className="bg-loss-red/10 border border-loss-red/30 rounded-lg p-6 mb-8">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-6 h-6 text-loss-red flex-shrink-0 mt-1" />
            <div>
              <h2 className="text-xl font-bold text-loss-red mb-2">Important Reminder</h2>
              <p className="text-text-muted">
                ParlayGuarantee is an <strong>information and entertainment service</strong>. We sell AI-generated sports predictions and opinions.
                We are not a sportsbook, do not accept wagers, and do not guarantee that you will profit from gambling.
                No sports prediction service can guarantee winning outcomes. All picks are opinions generated by AI models.
              </p>
            </div>
          </div>
        </div>

        <div className="prose prose-lg max-w-none">
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-accent-green mb-4">Know the Signs</h2>
            <p className="text-text-muted mb-4">
              Gambling can become a problem when it stops being entertainment. Watch for these warning signs:
            </p>
            <ul className="text-text-muted space-y-2">
              <li>Spending more money or time gambling than you intended</li>
              <li>Chasing losses — betting more to try to win back what you&apos;ve lost</li>
              <li>Borrowing money or selling possessions to gamble</li>
              <li>Neglecting work, school, family, or personal needs because of gambling</li>
              <li>Feeling restless or irritable when trying to cut back</li>
              <li>Lying to family or friends about how much you gamble</li>
              <li>Gambling to escape problems or relieve feelings of helplessness or anxiety</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-accent-green mb-4">Tips for Responsible Gambling</h2>
            <div className="grid md:grid-cols-2 gap-4">
              {[
                { title: 'Set a Budget', desc: 'Decide how much you can afford to lose before you start. Never bet money you need for bills, rent, or essentials.' },
                { title: 'Set Time Limits', desc: 'Decide in advance how much time you\'ll spend. Take regular breaks.' },
                { title: 'Never Chase Losses', desc: 'Accept losses as the cost of entertainment. Chasing losses leads to bigger losses.' },
                { title: 'Don\'t Bet Under the Influence', desc: 'Alcohol and drugs impair judgment. Make betting decisions with a clear head.' },
                { title: 'Balance Your Life', desc: 'Gambling should be one of many leisure activities, not your primary form of entertainment.' },
                { title: 'Take Breaks', desc: 'Step away regularly. If you find it hard to stop, that\'s a warning sign.' },
              ].map((tip, i) => (
                <div key={i} className="card p-4">
                  <h3 className="font-bold text-accent-gold mb-2">{tip.title}</h3>
                  <p className="text-sm text-text-muted">{tip.desc}</p>
                </div>
              ))}
            </div>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-accent-green mb-4">Get Help</h2>
            <p className="text-text-muted mb-6">
              If you or someone you know has a gambling problem, free and confidential help is available 24/7:
            </p>

            <div className="space-y-4">
              <div className="card p-6 border-accent-green/30">
                <div className="flex items-start gap-4">
                  <Phone className="w-8 h-8 text-accent-green flex-shrink-0" />
                  <div>
                    <h3 className="text-lg font-bold mb-1">National Council on Problem Gambling</h3>
                    <p className="text-2xl font-bold text-accent-green mb-2">
                      <a href="tel:1-800-522-4700">1-800-522-4700</a>
                    </p>
                    <p className="text-text-muted text-sm">Call or text 24/7. Free, confidential help.</p>
                  </div>
                </div>
              </div>

              <div className="card p-6 border-accent-gold/30">
                <div className="flex items-start gap-4">
                  <Globe className="w-8 h-8 text-accent-gold flex-shrink-0" />
                  <div>
                    <h3 className="text-lg font-bold mb-1">Online Resources</h3>
                    <ul className="text-text-muted space-y-2 mt-2">
                      <li>
                        <a href="https://www.ncpgambling.org" target="_blank" rel="noopener noreferrer" className="text-accent-green hover:underline">
                          ncpgambling.org
                        </a> — National Council on Problem Gambling
                      </li>
                      <li>
                        <a href="https://www.gamblersanonymous.org" target="_blank" rel="noopener noreferrer" className="text-accent-green hover:underline">
                          gamblersanonymous.org
                        </a> — Gamblers Anonymous
                      </li>
                      <li>
                        <a href="https://www.samhsa.gov/find-help/national-helpline" target="_blank" rel="noopener noreferrer" className="text-accent-green hover:underline">
                          SAMHSA National Helpline
                        </a> — 1-800-662-4357
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-accent-green mb-4">Self-Exclusion Tools</h2>
            <p className="text-text-muted mb-4">
              Most licensed sportsbooks offer self-exclusion programs that allow you to voluntarily ban yourself from placing bets for a set period. Contact your sportsbook directly or visit your state&apos;s gaming commission website for self-exclusion options.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold text-accent-green mb-4">Our Commitment</h2>
            <div className="bg-bg-secondary/30 p-6 rounded-lg border border-accent-green/20">
              <div className="flex items-start gap-3">
                <Shield className="w-6 h-6 text-accent-green flex-shrink-0 mt-1" />
                <div className="text-text-muted">
                  <p className="mb-3">ParlayGuarantee is committed to responsible gambling practices:</p>
                  <ul className="space-y-2">
                    <li>• We require all users to be 21+ and in a jurisdiction where sports betting is legal</li>
                    <li>• We clearly state that our picks are AI-generated opinions, not guaranteed outcomes</li>
                    <li>• We do not encourage excessive or irresponsible gambling</li>
                    <li>• We provide prominent links to problem gambling resources across our site</li>
                    <li>• Our refund policy exists to reduce financial risk — not to encourage more betting</li>
                  </ul>
                </div>
              </div>
            </div>
          </section>
        </div>

        <div className="mt-8 text-center">
          <Link href="/" className="btn-primary mr-4">Back to Home</Link>
          <Link href="/terms" className="btn-secondary">View Terms of Service</Link>
        </div>
      </div>
    </div>
  )
}
